version: '3.8'

services:
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_PORT: ${POSTGRES_PORT}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # backend:
  #   build:
  #     context: ./backend
  #   depends_on:
  #     - db
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_PORT: ${POSTGRES_PORT}
  #   ports:
  #     - "8000:8000"

  frontend:
    build:
      context: ./frontend
    # depends_on:
    #   - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
